feat: did stuff
NotCosmo/Vortex-V2 pull request #7
Opened 2022-09-28 13:03 UTC by H4ckerxx44

## Summary

1. Implemented userinfo / serverinfo commands
2. filled `.env` example file with values
3. fixed typos
4. made the bot runnable (on my machine at least) | cleaned up poetry stuff
5. added `.psd` file for "vortex" name from README.md
6. added some fun / info commands (penis, cat, dog, nasa apod, weather, whatpulse stats)
7. lots of smaller stuff

## Checklist:

- [x] This PR follows style guidelines (black, isort) of this project.
- [x] This PR has been tested.
- [] This PR fixes an issue.
- [x] This PR adds something new.
- [ ] This PR is **not** a code change (e.g. README, typos, ...)

2022-09-29 08:06 UTC, toolifelesstocode requested changes

2022-09-29 08:06 UTC, toolifelesstocode commented on src/cogs/fun.py
> +    async def mock(self, ctx: Context, *, msg):
```suggestion
    async def mock(self, ctx: Context, *, msg: str):
```

2022-09-29 08:06 UTC, toolifelesstocode commented on src/cogs/general.py
> +                name="Boosting stats", value=f"```Nitro level: {ctx.guild.premium_tier}\nBoost Count: {ctx.guild.premium_subscription_count}```", inline=False
```suggestion
                name="Boosting stats", value=f"```Boost level: {ctx.guild.premium_tier}\nBoost Count: {ctx.guild.premium_subscription_count}```", inline=False
```

2022-09-29 14:05 UTC, H4ckerxx44 commented on src/templates/template_cog.py
> +from nextcord import Member, Embed
I'd honestly say these are fine due to fact that this is a template for future use, these imports are used pretty frequently

2022-09-29 18:43 UTC, toolifelesstocode commented on src/templates/template_cog.py
> +from nextcord import Member, Embed
Sure. Although you could just leave it as `import nextcord`, if one _does_ need to import something from the `nextcord` module.

2022-09-29 18:46 UTC, H4ckerxx44 commented on src/templates/template_cog.py
> +from nextcord import Member, Embed
Sounds like a plan.

2022-09-29 19:12 UTC, toolifelesstocode commented on src/utility/util.py
> +        to_write = f"""from nextcord import Embed, Message, Member
```suggestion
        to_write = f"""
        from nextcord import Embed, Message, Member
```
or 
```suggestion
        to_write = inspect.dedent(f"""
        from nextcord import Embed, Message, Member
```
Since this would make the code look nicer with indentation, while `inspect.dedent` won't make it add any indentation publicly.

2022-10-01 18:11 UTC, ooliver1 requested changes

2022-10-01 18:11 UTC, ooliver1 commented on src/cogs/general.py
> +    info(f"{General.__class__.__name__} cog loaded.")
See comment from `Fun` cog, but wouldn't it make sense for the cog loading code to have this anyway, to reduce repetition.

2022-10-01 18:11 UTC, ooliver1 commented on src/constants.py
> +# TODO: to be filled out with stuff from your guild cosmo
Or it could be environment variables.

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/bot.py
> +        self.icon = "https://cdn.discordapp.com/avatars/926513310642339891/36f01c4d80398bccdcf1ac094e6af7c4.png?size=4096"
The bot's avatar is available via `bot.user.avatar.url`
> **Note**
> `bot.user` is only accessible after startup.

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/bot.py
> +        self.owner_id = int(os.getenv("BOT_OWNER_ID"))
[`owner_id` is also available after startup](https://docs.nextcord.dev/en/stable/ext/commands/api.html#nextcord.ext.commands.Bot.owner_id), or you can use [`Bot.is_owner`](https://docs.nextcord.dev/en/stable/ext/commands/api.html#nextcord.ext.commands.Bot.is_owner), which would accomodate for teams if that is ever used.

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/bot.py
> +        self.major_version = os.getenv("BOT_MAJOR_VERSION")
This could probably be parsed via `major, minor, patch = version.split(".")` then setting the attributes

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/bot.py
> +        self.main_color: int = 0xFFFFFF
The colour does not seem to be white - https://github.com/NotCosmo/Vortex-V2/pull/7/files#diff-67af13da50005ebb4d0f16b7b626eb35bd151b2a1649070fb94c45583cc3e3a4L18

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/bot.py
> +                response = await r.json()
Similar with the other API call, if `r.status` is not `200`, `response` is not defined.

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/util.py
> +    """
3 lines probably isnt necessary for 4 words
```suggestion
    """:return: string like `15:45:12`"""
```

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/util.py
> +def camel_case(string):
This is `PascalCase` specifically, instead of `camelCase`

2022-10-01 18:11 UTC, ooliver1 commented on src/utility/util.py
> +    with open(f"{path}\\cogs\\{cog_name}.py", "w") as f:
This should use `/`, to reduce platform lock. Windows APIs allow for `/`, and if they dont, you can use `pathlib.Path` - `Path(cwd) / "cogs" / cog_name` (yes, the div operator)

2022-10-01 18:32 UTC, toolifelesstocode requested changes

2022-10-01 18:32 UTC, toolifelesstocode commented on src/cogs/fun.py
> +    info(f"{Fun.__class__.__name__} cog loaded.")
^ This is correct, it would actually just say `CogMeta cog loaded.` on every part of the code where this is added.

2022-10-02 09:13 UTC, toolifelesstocode commented on src/cogs/fun.py
> +    info(f"{Fun.__class__.__name__} cog loaded.")
^ This is correct, it would actually just say `CogMeta cog loaded.` on every part of the code where this is added.

2022-10-02 14:01 UTC, H4ckerxx44 commented on src/constants.py
> +# TODO: to be filled out with stuff from your guild cosmo
That's really up to @NotCosmo to decide, I'm fine with both ways.
Though I believes environment variables should only be more "secret" stuff instead of API URLs or something like that.

2022-10-02 14:50 UTC, H4ckerxx44 commented on src/utility/bot.py
> +        self.owner_id = int(os.getenv("BOT_OWNER_ID"))
Well, I need the owner_id for the stats command, when I remove this from here it will be `<@None>` in the embed

2022-10-02 15:21 UTC, ooliver1 requested changes

2022-10-02 15:21 UTC, ooliver1 commented on src/cogs/fun.py
> +        )
```suggestion
        await ctx.send(str(cat)) if cat else "Getting a cat failed. How sad.")
```

2022-10-02 15:21 UTC, ooliver1 commented on src/cogs/fun.py
> +        )
```suggestion
        await ctx.send(str(dog)) if dog else "Getting a doggo failed, I feel miserable.")
```

2022-10-02 15:21 UTC, ooliver1 commented on src/cogs/general.py
> +        US_EPA_INDEX = {
These could be file/class-level constants instead of being defined every time

2022-10-02 15:21 UTC, ooliver1 commented on src/cogs/general.py
> +        except UnboundLocalError:
Maybe use an `else` where `r.status` is checked and `return`? Seems a bit sketch to catch the unbound error

2022-10-02 15:21 UTC, ooliver1 commented on src/cogs/general.py
> +            if r.status == 200:
This doesn't seem to be resolved

2022-10-02 16:25 UTC, H4ckerxx44 commented on src/cogs/general.py
> +            if r.status == 200:
This should be resolved now.

2022-10-03 15:21 UTC, merged

2022-10-04 08:53 UTC, toolifelesstocode commented
Waaaa merge commits